- app/build.gradle
- app/src/main/assets/pages/About.html
Changes:
- build.gradle now adds build datetime as a resource string ReleaseDateValue 
- About page now fetches data from ReleaseDateValue resource instead of fixed value
[https://openimis.atlassian.net/browse/OTC-242](
https://openimis.atlassian.net/browse/OTC-242)
> OTC-242: Automatically update version in About in Mobile Apps

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/Global.java
- app/src/main/java/org/openimis/imispolicies/MainActivity.java
- app/src/main/java/org/openimis/imispolicies/SQLHandler.java
- app/src/main/java/org/openimis/imispolicies/Token.java
Changes:
- Fixed how the file picker worked. Earlier it will only pull the file name, resulting in Master data import being possible only inside `IMIS/Database` directory. Now the file content is copied to app specific directory, so it can be fully managed.
- Added a solution to easily change privacy of specific IMIS subdirectories. Private directories will be created inside the `/data/` instead of `/storage/`. Moved `Authentications` and `Database` dirs to `/data/`
- Added a solution to get application context inside components that are not Android components. (i.e. `Token` class)
[https://openimis.atlassian.net/browse/OTC-75](https://openimis.atlassian.net/browse/OTC-75)
> OTC-75: Flexibility of loading of the Master Data off-line

- app/src/main/java/org/openimis/imispolicies/Acquire.java
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/Global.java
- app/src/main/java/org/openimis/imispolicies/MainActivity.java
- app/src/main/java/org/openimis/imispolicies/SQLHandler.java
Changes
- Acquiring photo from menu now updates local insuree on submit
- Automatic photo assignment now picks the newest photo of a insuree
- Changed some event handlers to lambda expressions
- Deleted unused legace code related to `CallSoap`
- Fixed update call of `SQLHandler`
[https://openimis.atlassian.net/browse/OP-354](https://openimis.atlassian.net/browse/OP-354)
> OP-354: Fix assigning photos to insurees in IMIS Policies

- app/src/main/res/layout/controls.xml
Changes:
- “Send SMS” checkbox in CN request checked by default
[https://openimis.atlassian.net/browse/OTC-267](https://openimis.atlassian.net/browse/OTC-267)
> OTC-267: Enforce Send SMS to yes in CN request

- app/src/main/assets/pages/Search.html
Currently used condition is opening login prompt when loged user tried to enter 'modify family' activity. Because of that user could never open the activity.
> Fix token condition in searching families

- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
TICKET: [OTC-313](https://openimis.atlassian.net/browse/OTC-313)
Assertion instead of exception caused execution freezing.
> OTC-313: Fixed issue with saving families pulled from server

- app/src/main/java/org/openimis/imispolicies/MainActivity.java
Changed:
- Set the `AllowFileAccess` flag to `true` in `WebView` initialization, as it can be set to `false` by default depending on Android version and phone manufacturer.
[https://openimis.atlassian.net/browse/OTC-309](https://openimis.atlassian.net/browse/OTC-309)
> OTC-309: If picture is taken with Acquire, it is not displayed with Enrol a new insuree with same CHFID

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/ControlNumberService.java
- app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java
- app/src/main/java/org/openimis/imispolicies/OverViewControlNumbers.java
- app/src/main/java/org/openimis/imispolicies/OverViewPolicies.java
Changes:
- Deleted a condition which was making every offline policy invisible after a CN request (allowing re-requesting a CN for offline policy)
- Fixed getRequestedPolicies for overview of CN when no upload date is selected 
- Streamlined and fixed error processing of CN request related code
- Deleted some unused code
[https://openimis.atlassian.net/browse/OTC-325](https://openimis.atlassian.net/browse/OTC-325)
> OTC-325: If there is an error when requesting CN, the state of policies should remain the same

- app/src/main/assets/pages/Family.html
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
Changes:
- Modified family enrolment response parsing to fit the new format
Additional changes:
- Modified JS interface to log which resource strings cannot be found
- Fixed mismatch of resource string names for `ApprovalOfSMS` and `LanguageOfSMS` fields
- Fixed wrong string comparation
[https://openimis.atlassian.net/browse/OTC-329](https://openimis.atlassian.net/browse/OTC-329)
> OTC-329: REST API POST Family should return HTTP 200 with db UUIDs in payload

- app/src/main/assets/pages/FamilyPolicies.html
- app/src/main/assets/pages/FamilyPolicies.js
- app/src/main/assets/pages/Policy.html
- app/src/main/assets/pages/Policy.js
- app/src/main/java/org/openimis/imispolicies/BulkControlNumbersActivity.java
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/ControlNumberService.java
- app/src/main/java/org/openimis/imispolicies/SQLHandler.java
- app/src/main/res/values/strings.xml
Changes:
- Fetched bulk control numbers are automatically assigned to policies after product is selected, in case there is no control numbers left the message is displayed.
- Assigned control numbers are attached to enrolment payload.
- Assigned control numbers are displayed in `FamiliPolicies` and `Policy` pages.
Additional adjustments:
- Added process dialog when fetching control numbers.
- Fixed assigned and free control number counts.
- Products after thier active period are not visible in bulk CN fetch view.
[https://openimis.atlassian.net/browse/OTC-372](https://openimis.atlassian.net/browse/OTC-372)
preview:
> OTC-372: Add auto-assigning of pre-fetched control numbers to policy during enrolment

- app/src/main/java/org/openimis/imispolicies/Acquire.java
Changes:
- Added event for clicking the back arror in `Acquire` page
- Fixed wrong `FileProvider` name
[https://openimis.atlassian.net/browse/OTC-377](https://openimis.atlassian.net/browse/OTC-377)
> OTC-337: MV app IMIS Policies: return frm the page Acquire doesn't funcion

- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
Changes:
- Added conversion from boolean to int for `Insuree` `isHead` field during family download
[https://openimis.atlassian.net/browse/OTC-378](https://openimis.atlassian.net/browse/OTC-378)
> OTC-378: MV;IMIS Policies not possible to save a policy

- app/src/main/java/org/openimis/imispolicies/Renewal.java
Changes:
- Fixed a bug regarding updating a view on separate thread
[https://openimis.atlassian.net/browse/OTC-485](https://openimis.atlassian.net/browse/OTC-485)
> OTC-485: App crashes when saving an ulisted renewal

- .github/workflows/manual.yml
- app/build.gradle
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/ToRestApi.java
- run_cli.sh
Improve manual build, add gradle cache, add android cache (this has the huge benefit of keeping the debug keystore so that you can upgrade the apks generated by the actions.
Also improved error logging in the app itself so that error don't get completely swallowed. An improvement would be to report those to the UI with a "debug" parameter or something similar.
> Niger and a bit more

- app/src/main/assets/pages/Policy.html
- app/src/main/assets/pages/Policy.js
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/Renewal.java
- app/src/main/res/values/strings.xml
Changes:
- Changed CN fields in Enrolment and Renewal to allow modifying auto-filled CN
- Added confirm dialog in Enrolment and Renewal after saving a policy with unknown CN
[https://openimis.atlassian.net/browse/OTC-494](https://openimis.atlassian.net/browse/OTC-494)
> OTC-494: Fixed CN text fields in Enrolment and Renewal

- .github/workflows/manual.yml
- app/build.gradle
- app/src/main/assets/JSON/hflevels.json
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/Global.java
- app/src/main/java/org/openimis/imispolicies/MainActivity.java
- app/src/main/java/org/openimis/imispolicies/Renewal.java
- app/src/main/res/layout-v21/renewal.xml
- app/src/main/res/layout/renewal.xml
- app/src/master/res/values-fr/strings.xml
- app/src/niger/assets/JSON/hflevels.json
- app/src/niger/java/org/openimis/imispolicies/Escape.java
- script-git-version.gradle
* Build issue in transitive dependency
* HF levels are externalised so that they can be adapted per country. This could be used for other lists later.
* When clicking the picture in the enrolment, it used to offer to attach an existing picture, now the chooser also offers to use the camera. This was tested on recent devices but also on older ones because the detection of the chosen action has different behaviors there.
* QR codes can now be scanned when manually entering a renewal.
> Niger improvements

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/RenewList.java
- app/src/main/java/org/openimis/imispolicies/SQLHandler.java
- app/src/main/java/org/openimis/imispolicies/Util.java
- app/src/main/res/values/strings.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- script-git-version.gradle
Changes:
- Updated renewal extreact import feature to work with Android 10/11 filesystem security
- Chaged hard-coded strings used in renewal extreact import to string resources
- Fixed missing string resources in `Settings` page
Maintenance:
- removad all references to `Jcenter` repository (read-only from March 31st, 2021, replaced with `Maven`)
- Bumped Java version to 11 (LTS) (Packaged with newest stable version of Android Studio, also required by one dependency, does not break compability with older versions of Android)
- Bumped Gradle varsion to 7.0.2
> OP-187: IMIS web and policies app: Renewal extracts dont work

- app/build.gradle
- app/src/main/assets/pages/Settings.html
- app/src/main/assets/pages/Settings.js
- app/src/main/java/org/openimis/imispolicies/Acquire.java
- app/src/main/java/org/openimis/imispolicies/BulkControlNumbersActivity.java
- app/src/main/java/org/openimis/imispolicies/CheckCommission.java
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/Compressor.java
- app/src/main/java/org/openimis/imispolicies/ControlNumberService.java
- app/src/main/java/org/openimis/imispolicies/Enquire.java
- app/src/main/java/org/openimis/imispolicies/Global.java
- app/src/main/java/org/openimis/imispolicies/MainActivity.java
- app/src/main/java/org/openimis/imispolicies/OutputStreamImageTarget.java
- app/src/main/java/org/openimis/imispolicies/RenewList.java
- app/src/main/java/org/openimis/imispolicies/Renewal.java
- app/src/main/java/org/openimis/imispolicies/SQLHandler.java
- app/src/main/java/org/openimis/imispolicies/ToRestApi.java
- app/src/main/java/org/openimis/imispolicies/tools/Log.java
- app/src/main/java/org/openimis/imispolicies/tools/Util.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/paths.xml
- app/src/niger/java/org/openimis/imispolicies/Escape.java
[https://openimis.atlassian.net/browse/OTC-508](https://openimis.atlassian.net/browse/OTC-508)
Changes:
- Implemented logger wrapper, allowing to perform additional logic during log calls (like saving logs aboce a certain level to a file)
- Replaced all `Log` calls with a wrapper.
- Added a feature do share/send a file from policies app to other apps (like email app)
> OTC-508: Test insuree image upload from Android 7

- .gitignore
- app/build.gradle
- app/src/debug/java/org/openimis/imispolicies/tools/Log.java
- app/src/main/assets/pages/Settings.html
- app/src/main/assets/pages/Settings.js
- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
- app/src/main/java/org/openimis/imispolicies/Global.java
- app/src/release/java/org/openimis/imispolicies/tools/Log.java
[https://openimis.atlassian.net/browse/OTC-529](https://openimis.atlassian.net/browse/OTC-529)
Changes:
- Moved logging framework into a debug build
- Added an empty version of the logging framework to release build
- Disabled the logging related buttons in settings on the release build
- Removed `release/` part from `gitignore`. This section is not a part of gradle project structure and it prevents for `release` build specific code and resources from being commited.
> OTC-529 Remove logging framework from release version of the app

- app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
https://openimis.atlassian.net/browse/OTC-536
Changes:
- Using method created in utils, app now checks whether phone number of a given insuree exists, before trying to save it in the db
> OTC-536: Added check for empty value of phone number of an insuree

- app/src/main/java/org/openimis/imispolicies/Renewal.java
https://openimis.atlassian.net/browse/OTC-582
Changes:
- Unfilled position in renewal form now doesn't crash the app
- Warnings about missing data now display properly
> OTC-582: Input checks for new renewals now are displayed properly.

- app/src/main/java/org/openimis/imispolicies/Enquire.java
- app/src/main/res/values/strings.xml
https://openimis.atlassian.net/browse/OTC-581
Changes:
- Changed message when using enquire function on insuree with no active policy.
- Instead of null the message says that no active policy is registered.
- Function checks for expiryDate and compares it to null, since it was the variable that originally generated "null" message.
> OTC-581: Custom message is now displayed when no policy is active.
