app/src/main/java/org/openimis/imispolicies/Escape.java

Related to:
https://openimis.atlassian.net/browse/OS-32

OS-32: Offline data files encryption in Mobile Applications

---

app/build.gradle
app/src/main/java/org/openimis/imispolicies/SQLHandler.java

Task: 
https://openimis.atlassian.net/browse/OP-118

OP-118: Added support for Android 9

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/openimis/imispolicies/CheckCommission.java
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/ControlNumbers.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverviewAdapter.java
app/src/main/java/org/openimis/imispolicies/OverViewControlNumbers.java
app/src/main/java/org/openimis/imispolicies/OverViewPolicies1.java
app/src/main/java/org/openimis/imispolicies/SQLHandler.java
app/src/main/java/org/openimis/imispolicies/SearchNotEnrolledPolicies.java
app/src/main/java/org/openimis/imispolicies/ToRestApi.java
app/src/main/res/layout/activity_control_numbers.xml
app/src/main/res/layout/not_enrolled_policies_overview.xml
app/src/main/res/layout/request_for_not_enrolled_policies.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Related ticket: https://openimis.atlassian.net/browse/OTC-63

OTC-63: Acquiring control numbers before enrolment

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java
app/src/main/java/org/openimis/imispolicies/OverViewPolicies1.java
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Related ticket: https://openimis.atlassian.net/browse/OTC-120

OTC-120: Added checking of uniqueness of policies products

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/ToRestApi.java

TICKET: [OP-262](https://openimis.atlassian.net/browse/OP-262)

OP-262: Catch app breaking exception and display information about missing photo

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/CummulativeIndicators.java
app/src/main/java/org/openimis/imispolicies/SQLHandler.java

TICKET: [OP-284](https://openimis.atlassian.net/browse/OP-284)

OP-284: Fixed IDs overlaping

---

app/src/main/assets/pages/Login.html
app/src/main/java/org/openimis/imispolicies/CheckCommission.java
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/CummulativeIndicators.java
app/src/main/java/org/openimis/imispolicies/FeedbackList.java
app/src/main/java/org/openimis/imispolicies/MainActivity.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java
app/src/main/java/org/openimis/imispolicies/OverViewControlNumbers.java
app/src/main/java/org/openimis/imispolicies/OverViewPolicies.java
app/src/main/java/org/openimis/imispolicies/RenewList.java
app/src/main/java/org/openimis/imispolicies/Reports.java
app/src/main/java/org/openimis/imispolicies/SnapshotIndicators.java
app/src/main/java/org/openimis/imispolicies/Statistics.java

TICKET: [OP-188](https://openimis.atlassian.net/browse/OP-188)

OP-188: Added accurate connectivity error messages

---

app/src/main/AndroidManifest.xml

TICKET: [OP-283](https://openimis.atlassian.net/browse/OP-283)

OP-283: Exclude unnecessary permissions in manifest

---

app/src/main/java/org/openimis/imispolicies/Enquire.java
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml

TICKET: [OP-264](https://openimis.atlassian.net/browse/OP-264)

OP-264: Fix display names for enquire values

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java

TICKET: [OP-269](https://openimis.atlassian.net/browse/OP-269)

OP-269: Photos included in creating XML Enrolment

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/MainActivity.java

TICKET: [OP-194](https://openimis.atlassian.net/browse/OP-194)

OP-194: Ensure user logged in report activity

---

app/src/main/java/org/openimis/imispolicies/Enquire.java
app/src/main/res/layout/policylist.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml

TICKET: [OP-220](https://github.com/openimis/claims_android_app_java/pull/23)

OP-220: Added missing field for enquiry function

---

app/src/main/java/org/openimis/imispolicies/MainActivity.java

Added option to reselect current language.
https://openimis.atlassian.net/browse/OTC-290

OP-290: Select language can be done for currently selected one

---

README.md
app/build.gradle
app/src/bepha/res/values-fr/strings.xml
app/src/bepha/res/values/strings.xml
app/src/chf/res/values-sw/strings.xml
app/src/chf/res/values/strings.xml
app/src/demo/res/values-fr/strings.xml
app/src/main/AndroidManifest.xml
app/src/main/assets/pages/About.html
app/src/main/res/layout/nav_header_main.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/xml/searchable.xml

changes:
- Changed app name to reference `app_name_policies` to avoid conflict with imported libraries
- Deleted every key `app_name` in resources 
- Made app name assignable only in build.gradle file

OTC-238: Policies app name changed to "Barcode Scanner" in unsupported languages

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/Feedback.java
app/src/main/java/org/openimis/imispolicies/FeedbackList.java
app/src/main/java/org/openimis/imispolicies/Global.java
app/src/main/java/org/openimis/imispolicies/MainActivity.java
app/src/main/java/org/openimis/imispolicies/RenewList.java
app/src/main/java/org/openimis/imispolicies/Renewal.java
app/src/main/java/org/openimis/imispolicies/SQLHandler.java
app/src/main/java/org/openimis/imispolicies/Token.java

Changes:
- Changed the build.gradle to target and compile against API level 30
- Moved all acces to `"/IMIS/"` from `Environment.getExternalStorageDirectory().getAbsolutePath()` to `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS)`, effectively moving IMIS directory from External Storage root to Documents.
- Routed all External Storage access to `Global` class
- Added `MANAGE_EXTERNAL_STORAGE` permission (Android 11)
- Added IMIS main directory name dependent on build variant
https://openimis.atlassian.net/browse/OP-315

OP-315: Android 10/11 compatibility

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java

TICKET: https://openimis.atlassian.net/browse/OP-322
It was the issue with payload for "uploadEnrollment" - 'policy' part.

OP-322: fixed add a new member to a family

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java

TICKET: https://openimis.atlassian.net/browse/OP-324
RELATED PR: https://github.com/openimis/database_ms_sqlserver/pull/66 - here is my proposition to process 'deleting' insuree from family. 
One of the issue was with deleting from phone existing member of family which was from "online".
Now we can delete from list the insuree written in web app

OP-324: delete an existing member of a family - problem on family list

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/SQLHandler.java

Changes:
- Made offline master data import compatible with API format.
- Fixed importing master data in old format (for backwards compatibility)
- Deleted unnecessary exception throw from SQLHandler which prevented the database from being properly closed
[https://openimis.atlassian.net/browse/OP-325](https://openimis.atlassian.net/browse/OP-325)

OP-325: Test case: update the master data in offline mode 

---

app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java

TICKET: [OTC-265](https://openimis.atlassian.net/browse/OTC-265)

OTC-265: Fixed multiple policies selection in CN Request

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml

TICKET: https://openimis.atlassian.net/browse/OTC-312
Added such 'Progress Dialog' during processing sync.

OTC-312: added progress dialog in sync

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java

TICKET: [OTC-314](https://openimis.atlassian.net/browse/OTC-314)

OTC-314: Fixed issue with sending empty confirmationType as "null"

---

app/src/chf/res/values/strings.xml
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverviewAdapter.java
app/src/main/res/layout/not_enrolled_policies_overview.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml

TICKET: [OTC-306](https://openimis.atlassian.net/browse/OTC-306)

 @malinowskikam OTC-306: Select all button and routine added 

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java

TICKET: [OTC-317](https://openimis.atlassian.net/browse/OTC-317)

OTC-317: Query breaking XML Enrollments fixed

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java

TICKET: https://openimis.atlassian.net/browse/OTC-320
fix "Not unique Product error when requesting CN for offline policies"

OTC-320: only one productCode should be in list of unique codes

---

app/src/main/java/org/openimis/imispolicies/CheckCommission.java

Changes:
- Fixed how report modes are translated to codes
- Changed order of modes in drop down to match the rest of the system
[https://openimis.atlassian.net/browse/OTC-324](https://openimis.atlassian.net/browse/OTC-324)

OTC-324: Fix check commission functionality

---

app/build.gradle
app/src/main/java/org/openimis/imispolicies/Acquire.java
app/src/main/java/org/openimis/imispolicies/SQLHandler.java

Changes:
- Cleaned 3 nearly identical `ShowDialog` methods
- Fixed some error-prone code
- Deleted direct references to libraries in `/libs/` directory, extended wildcard import
- deleted copied `allproject` configuration in `app/build.gradle`
[https://openimis.atlassian.net/browse/OTC-137](https://openimis.atlassian.net/browse/OTC-137)

OTC-137: Cleaning code in Acquire.java, build.gradle

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/OverViewPolicies.java
app/src/main/java/org/openimis/imispolicies/SearchOverViewPolicies.java
app/src/main/res/layout/activity_over_view_policies.xml

Changes:
- Many interface implementations changed to lambda expressions for simplicity
- Query to search for online policies now only returns entries with uploaded date not empty (not showing not synced enrolments)
- Query to search for online policies now correctly applies date interval
- Query to search for online policies now correctly searches for product code instead of a product name
- IDs and names of some buttons and fields changed from generic to reflecting actual functionality
- Some unused code deleted
[https://openimis.atlassian.net/browse/OTC-331](https://openimis.atlassian.net/browse/OTC-331)

OTC-331: Fix searching for online policies form

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverviewAdapter.java
app/src/main/java/org/openimis/imispolicies/OverViewControlNumberAdapter.java
app/src/main/java/org/openimis/imispolicies/OverViewControlNumbers.java
app/src/main/java/org/openimis/imispolicies/SearchNotEnrolledPolicies.java
app/src/main/java/org/openimis/imispolicies/SearchOverViewControlNumber.java
app/src/main/java/org/openimis/imispolicies/SearchOverViewPolicies.java
app/src/main/res/layout/activity_over_view_control_numbers.xml

Changes:
- Fixed the query for CN requests to correctly apply upload and request date filters
- Fixed the product filter in query for CN requests
- Changed some variable names and UI elements IDs to fit their role.
Additional Changes:
- Automatic code style correction by Android Studio (highly inflating number of lines changes with only style change)
- Changed some interface implementations to lambda expressions for simplicity
- Deleted some unused/commented code
[https://openimis.atlassian.net/browse/OTC-332](https://openimis.atlassian.net/browse/OTC-332)

OTC-332: Fixed search in Overview CN, code cleaning

---

app/src/bepha/res/values-fr/strings.xml
app/src/bepha/res/values/strings.xml
app/src/chf/res/values-sw/strings.xml
app/src/chf/res/values/strings.xml
app/src/main/assets/pages/Premium.js
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml

Changes:
- Changed string value with id `Confirm` from text `"Delete"` to `"Confirm"`
- Changed alert on policy value exceeded from default javascript `confirm()` to a customizable dialog
[https://openimis.atlassian.net/browse/OTC-153](https://openimis.atlassian.net/browse/OTC-153)

OTC-153: Changed alert on policy value exceeded to dialog

---

app/build.gradle

Changes:
- `API_VERSION` Changed to 3

MV build upgraded to use APIv3

---

app/src/main/java/org/openimis/imispolicies/SQLHandler.java

- Bulk CN queries will work when product codes returned from API are different case than products saved on phone

Fixed case specific queries for bulk CN 

---

app/src/main/java/org/openimis/imispolicies/Enquire.java

Changes:
- Added support for base64 images in for enquire functionality
- cleaned `Enquire.java`
[https://openimis.atlassian.net/browse/OTC-376](https://openimis.atlassian.net/browse/OTC-376)

OTC-376: MV app Policy: photos are not retrived by the Enquiry function

---

app/src/main/java/org/openimis/imispolicies/RenewList.java

Changes:
- Changed datafield used as a source for renewal prompt list from `EnrollDate` to `RenewalPromptDate`
- Added missing error handling for renewal prompt API request
- Cleaned `RenewList.java`
[https://openimis.atlassian.net/browse/OTC-414](https://openimis.atlassian.net/browse/OTC-414)

OTC-414: The dates of expiry of policies are not displayed (there is 0 instead)

---

app/build.gradle
app/src/main/java/org/openimis/imispolicies/AppInformation.java
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/MainActivity.java
app/src/main/java/org/openimis/imispolicies/OverViewControlNumbers.java
app/src/main/java/org/openimis/imispolicies/OverViewPolicies.java
app/src/main/java/org/openimis/imispolicies/RenewList.java
app/src/main/java/org/openimis/imispolicies/Renewal.java
app/src/main/java/org/openimis/imispolicies/SQLHandler.java
app/src/main/java/org/openimis/imispolicies/SearchOverViewControlNumber.java
app/src/main/java/org/openimis/imispolicies/Statistics.java
app/src/main/java/org/openimis/imispolicies/Token.java

Changes:
- Created `Appinformation.DateTimeInfo` class for access to default date and time formats and formatters
- Moved all occurances of default date format to `Appinformation.DateTimeInfo` class
- Cleaned `Renewal.java`
[https://openimis.atlassian.net/browse/OTC-430](https://openimis.atlassian.net/browse/OTC-430)

OTC-430: Moved default date format to AppInformation

---

app/src/main/assets/pages/Premium.js

Changes:
- Fixed Balance calculation when additional contributions are added
- Fixed policy being active after contribution modification
[https://openimis.atlassian.net/browse/OP-422](https://openimis.atlassian.net/browse/OP-422)

OP-442: If total contribution match policy value, the policy is not activated

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/Enquire.java
app/src/main/java/org/openimis/imispolicies/Util.java

Changes:
- Added  `Util` class for simple repeating code
- Fixed checking for empty photo during enquire and family download
[https://openimis.atlassian.net/browse/OTC-456](https://openimis.atlassian.net/browse/OTC-456)

OTC-456: Fixed downloading insuree without a photo

---

app/src/main/java/org/openimis/imispolicies/AppInformation.java
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/Renewal.java
app/src/main/java/org/openimis/imispolicies/Util.java
app/src/main/res/layout-v21/renewal.xml
app/src/main/res/layout/renewal.xml

Changes:
- Added control number field to the renewal form
- Added control number assigning for renewals (similar to enrolment)
- Added control number to renewal payload
- Fixed response handling after sending policy discontinue
[https://openimis.atlassian.net/browse/OTC-461](https://openimis.atlassian.net/browse/OTC-461)

OTC-461: Added bulk control numbers to renewals

---

app/src/bepha/res/values-fr/strings.xml
app/src/bepha/res/values/strings.xml
app/src/chf/res/values-sw/strings.xml
app/src/chf/res/values/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml
app/src/tchad/res/values-fr/strings.xml

Resource update (from localise)

---

.github/workflows/main.yml
.github/workflows/manual.yml

Changes:
- Java version used in github actions updated to 11 to match project requirements

Java version in github worflows updated to 11

---

app/build.gradle

Changes:
- removed unused values from build.gradle

build.gradle cleaned

---

app/src/main/res/values/strings.xml

Changes:
- added missing key to the default translation

Added missing string key

---

app/src/chf/res/values/strings.xml
app/src/main/assets/JSON/default_ints.json
app/src/main/java/org/openimis/imispolicies/BulkControlNumbersActivity.java
app/src/main/java/org/openimis/imispolicies/ControlNumberService.java
app/src/main/res/values-en-rTZ/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml

[https://openimis.atlassian.net/browse/OTC-510](https://openimis.atlassian.net/browse/OTC-510)
Changes:
- Removed app managed CN threshold
- Added support for API managed CN threshold
- Added additional status messages

OTC-510: Allow to max threshold for CNs any time

---

app/build.gradle
app/src/main/java/org/openimis/imispolicies/Acquire.java
app/src/main/java/org/openimis/imispolicies/Enquire.java
app/src/main/java/org/openimis/imispolicies/OutputStreamImageTarget.java
app/src/main/java/org/openimis/imispolicies/tools/Log.java

[https://openimis.atlassian.net/browse/OTC-498](https://openimis.atlassian.net/browse/OTC-498)
Changes:
- Updated picasso library to 2.71828
- Updated picasso library calls to adjust for API changes
- Moved log file names to constants

OTC-498 Updated picasso library to 2.71828

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/SQLHandler.java

https://openimis.atlassian.net/browse/OTC-374
Changes:
- Obsolete code removed
- Function renamed to be more informative (getResultXML2 ->getExportAsXML)

OTC-374: XMLexport function renamed. Obsolete code removed.

---

app/src/main/assets/pages/Enrollment.js
app/src/main/assets/pages/FamilyPolicies.js
app/src/main/assets/pages/Policy.js
app/src/main/assets/pages/Premium.js
app/src/main/res/values/strings.xml

https://openimis.atlassian.net/browse/OTC-344
Changes:
- Button labels added to resources and can now be translated.

OTC-344: Dialog button labels no longer hardcoded.

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/res/values/strings.xml

[https://openimis.atlassian.net/browse/OTC-546](https://openimis.atlassian.net/browse/OTC-546)
Changes:
- Added checks for AllowFamilyWithoutPolicy default field
- Split policy and contribution validation (previously app assumed contribution required == polisy required and vice versa)

OTC-546: AllowFamilyWithoutPolicy not implemented

---

app/build.gradle

Changes:
- Updated Release URL

Release URL update

---

app/src/main/java/org/openimis/imispolicies/CheckCommission.java
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/MainActivity.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java
app/src/main/java/org/openimis/imispolicies/OverViewControlNumbers.java
app/src/main/java/org/openimis/imispolicies/OverViewPolicies.java
app/src/main/java/org/openimis/imispolicies/Token.java

https://openimis.atlassian.net/browse/OTC-566
Changes:
- Method checking credentials now also checks if eocode has changed in the past
- EOCode now is saved in separate file on the phone

OTC-566: Resetting EO credentials after typing different EO code.

---

app/src/main/AndroidManifest.xml

Changes:
- Removed unused permissions

Removed unused permissions

---

app/src/main/assets/pages/Insuree.html

https://openimis.atlassian.net/browse/OTC-334
Changes:
- Vulnerabity field in the insuree moved to a position matching webapp form.

OTC-344: Vulnerability field moved to match webapp position.

---

app/src/debug/java/org/openimis/imispolicies/tools/Log.java
app/src/main/java/org/openimis/imispolicies/RenewList.java
app/src/main/java/org/openimis/imispolicies/tools/Compressor.java
app/src/main/java/org/openimis/imispolicies/tools/ImageManager.java
app/src/main/java/org/openimis/imispolicies/tools/StorageManager.java
app/src/main/java/org/openimis/imispolicies/tools/Util.java

[https://openimis.atlassian.net/browse/OP-764](https://openimis.atlassian.net/browse/OP-764)
Changes:
- Created `StorageManager`, an utility containing helper methods to use `Storage Access Framework` correctly
- Extended `File`, `Uri`, and `Stream` utilities with new functionality
- Moved `Compressor` class to `tools`
This PR does not modify any of the apps features. It only contains the tested toolset to update the file IO.

OP-764 Prepare a solution for file IO for mobile apps compliant with Google's external storage permissions

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java

[https://openimis.atlassian.net/browse/OTC-640](https://openimis.atlassian.net/browse/OTC-640)
Changes: 
- renamed `DownloadFamilyData` to `parseFamilyData` to better describe the function.
- Fixed error handling in `ModifyFamily` causing the method to freeze on `IOException`
- Removed infinite loop in `ModifuFamily`
- Added extra check for malformed photo path in `parseFamilyData`

OTC-640 The app freezes when using "Modify Family"

---

app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/SQLHandler.java

[https://openimis.atlassian.net/browse/OTC-642](https://openimis.atlassian.net/browse/OTC-642)
Changes:
- Fixed creation of XML enrolment files (missing photos and insurees)

OTC-642: Fixed XML enrolment export

---

app/build.gradle
app/src/main/assets/pages/Insuree.js
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/Enquire.java
app/src/main/java/org/openimis/imispolicies/util/JsonUtils.java

[https://openimis.atlassian.net/browse/OTC-683](https://openimis.atlassian.net/browse/OTC-683)
Changes:
- Introduced `JsonUtils.getStringOrDefault`
- Updated Enquire render code to replace `null` strings with empty strings/zeros
- Fixed InsureePolicy not being added to Insuree after policy is added but not activated (CHF case)
- Fixed Insuree form not getting closed on save when `InsureeId = 6` and `InsureeId = 7`
Additional changes:
- Replaced org.apache.http.legacy static file import with gradle reference

OTC-683 The CHF-ID number was seen Null I on the status

---

app/src/main/assets/pages/Insuree.js

[https://openimis.atlassian.net/browse/OTC-683](https://openimis.atlassian.net/browse/OTC-683)
Changes:
- Added additional policy check to `Insuree` page, fixing the page not closing if there is no policy

OTC-683 Added policy check to insuree page

---

app/src/main/java/org/openimis/imispolicies/Enquire.java
app/src/main/res/layout/activity_enquire.xml
app/src/main/res/values/strings.xml

Ticket: https://openimis.atlassian.net/browse/OP-687
Changes:
- Enquire functionality now checks whether insuree is covered by policy or not
- Label added to display this information

OP-703: Policy status is displayed in the Enquire menu.

---

app/build.gradle
app/custom-flavours.gradle.dist
app/src/main/AndroidManifest.xml
app/src/main/java/org/openimis/imispolicies/CheckCommission.java
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
app/src/main/java/org/openimis/imispolicies/ControlNumberService.java
app/src/main/java/org/openimis/imispolicies/CumulativeIndicators.java
app/src/main/java/org/openimis/imispolicies/Global.java
app/src/main/java/org/openimis/imispolicies/MainActivity.java
app/src/main/java/org/openimis/imispolicies/NotEnrolledPoliciesOverview.java
app/src/main/java/org/openimis/imispolicies/OverViewControlNumbers.java
app/src/main/java/org/openimis/imispolicies/OverViewPolicies.java
app/src/main/java/org/openimis/imispolicies/RenewList.java
app/src/main/java/org/openimis/imispolicies/Renewal.java
app/src/main/java/org/openimis/imispolicies/SnapshotIndicators.java
app/src/main/java/org/openimis/imispolicies/Statistics.java
app/src/main/java/org/openimis/imispolicies/ToRestApi.java
app/src/main/res/values-en-rCM/strings.xml
app/src/main/res/values-en-rTZ/strings.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values-fr-rCM/strings.xml
app/src/main/res/values-fr-rMR/strings.xml
app/src/main/res/values-fr-rNE/strings.xml
app/src/main/res/values-fr-rTD/strings.xml
app/src/main/res/values-fr-rcd/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-sw/strings.xml
app/src/main/res/values/strings.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Changes:
- Updated Android API version to `33`
- Removed `APP_DIR` build config field
- Changed `org.apache.http` to `cz.msebera.android.httpclient` library. This is a repackage of apache library with changed package path. This allows it to be imported without class name clash.
- Updated Gradle to 7.2.2
- Updated string resources

Updated SDK to 33, updated strings

---

app/src/main/java/org/openimis/imispolicies/Enquire.java

Ticket: https://openimis.atlassian.net/browse/OP-705
Changes:
- Message is added when no insuree is found or connection error occured
- Network code is rewritten to follow this feature in claims app

OP-705: Message added when no insuree is found in Enquire.

---

app/src/main/java/org/openimis/imispolicies/RenewList.java

Ticket: https://openimis.atlassian.net/browse/OP-687
Changes:
- In the Renewals section, if no renewals are found, the message is displayed.

OP-687: No renewals found message added.

---

app/build.gradle
app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java

[https://openimis.atlassian.net/browse/OP-940](https://openimis.atlassian.net/browse/OP-940)
Changes:
- Updated release URL
- Fixed region-assigned products

OP-940 Test mobiles apps on release server (22.10 Release)
